### PR TITLE
add jft to sms repsonse #147

### PR DESCRIPTION
**Pull request by pjaudiomv**
ref #147

### CODE REVIEW

**Comment by pjaudiomv** [comment]
this is tested and works great, couldnt reuse existing jft function though could create another if that makes more sense

**Comment by radius314** [comment]
why not just text the link?

**Comment by pjaudiomv** [comment]
damn thats a good point

**Comment by pjaudiomv** [comment]
actually that would go against my additional context from #147 ha. is the length the sticking point for wanting to just send a link?

**Comment by radius314** [comment]
One issue that we might run into with the 160 limit is sequencing.  I
suggest adding sequence numbers.

**Comment by pjaudiomv** [comment]
Ah yes so sms showing up out of order

**Comment by radius314** [comment]
Yes it’s likely that we’d get sequencing issues because we are sending out a couple of SMS all at once and the carrier may deliver out of order.  It’d be good to start each “page” with (1/4): for example for page 1 of 4.

**Comment by radius314** [comment]
In general this would be good as a “function” that could be reused and applied to other SMS.  Especially I’m thinking about adding an option to include location info field, which may push some other SMS messages beyond the 160 limit.  Australia has already mentioned that this is happening.

**Comment by pjaudiomv** [comment]
If the jft was added as a function it would be easier to send default Lang option and spit out the correct jft also

**Comment by radius314** [comment]
It should be two different function.  One for the JFT.  And one for
splitting SMS up.  The JFT could call the SMS process function.  They are
mutually exclusive and would allow the splitting function to be used
independent of the JFT function.

**Comment by pjaudiomv** [comment]
twillio is saying theyll do this automatically
https://support.twilio.com/hc/en-us/articles/223181508-Does-Twilio-support-concatenated-SMS-messages-or-messages-over-160-characters-

**Comment by pjaudiomv** [comment]
Ah wait we're not making use of the message resource uri

**Comment by pjaudiomv** [comment]
Maybe we should instead of using <Sms> verb

**Comment by radius314** [comment]
I think they are the same thing.  Looks like Sms might be deprecated.

**Comment by radius314** [comment]
Let’s test this out for a bit and see how it goes.

**Comment by pjaudiomv** [comment]
cool ill have to get a hold of my grandmas flip phone to try it out too ha

**Pull request merged**
