### PR TITLE
added help response

### PR DESCRIPTION
**Pull request by pjaudiomv**
Although you could end up going pretty far down the rabbit hole with responses if you wanted, I thought it may not be bad to have a help response to point to either here or maybe facebook page.

### CODE REVIEW

**Comment by radius314** [comment]
What would this look like?

**Comment by radius314** [comment]
Is the context here the messenger bot?

**Comment by pjaudiomv** [comment]
sorry if you typed help it would say something like "To find more information on this messenger app visit https://github.com/radius314/yap"

**Comment by pjaudiomv** [comment]
yes messenger bot

**Comment by radius314** [comment]
There is already something sort of like this.

**Comment by pjaudiomv** [comment]
what is that, i know when you do a search and there is no bmlt within a hundred miles it points you to do i have the bmlt. I was just thinking if someone asked the bot itself for help. but yea maybe bad idea, rabbit hole.

**Comment by radius314** [comment]
img_0319

**Comment by radius314** [comment]
deployed to archsearch

**Comment by pjaudiomv** [comment]
gotcha, i gotta stop using messenger on my computer, it looks a little different.

**Pull request merged**
